---
- name: centos | installing lvm2
  package:
    name: lvm2
    state: present
  become: true

- name: centos | installing sg3_utils
  package:
    name: sg3_utils
    state: present
  become: true

- name: centos | install xfs tools
  package:
    name: xfsprogs
    state: present
  become: true
  loop: "{{ lvm_groups|subelements('lvnames') }}"
  when:
    - item.1 is defined
    - item.1 != 'None'
    - item.1.filesystem is defined
    - item.1.filesystem == "xfs"
    - item.1.create is defined
    - item.1.create|bool

- name: centos | checking for scsi devices
  command: sg_scan
  become: true
  register: scsi_devices
  changed_when: false

- name: centos | rescanning for new disks
  command: /usr/bin/rescan-scsi-bus.sh
  become: true
  changed_when: false
