---
- name: create_vg | creating new LVM volume group(s)
  lvg:
    vg: "{{ item.vgname }}"
    pvs: "{{ item.disks | join(',') }}"
    state: present
  become: true
  loop: "{{ lvm_groups }}"
  when:
    - item.create is defined
    - item.create|bool
